let questions = [{
        question: "How many planets are in our solar system?",
        choice1: "8",
        choice2: "2",
        choice3: "7",
        choice4: "5",
        answer: "8",
    },
    {
        question: "How big is the Sun?",
        choice1: "1 million kilometers",
        choice2: "4 million kilometers",
        choice3: "1.4 million kilometers",
        choice4: "1.9 million kilometers",
        answer: "1.4 million kilometers",
    },
    {
        question: "What are the smallest in our solar system?",
        choice1: " Jupiter.",
        choice2: "Venus",
        choice3: "Mars",
        choice4: "MERCURY",
        answer: "MERCURY",
    },
    {
        question: "What are the largest planets in our solar system?",
        choice1: " Jupiter.",
        choice2: "Venus",
        choice3: "Mars",
        choice4: "MERCURY",
        answer: " Jupiter.",
    },
    {
        question: " Which planet is the fastest in the solar system",
        choice1: "Jupiter",
        choice2: " sun ",
        choice3: "earth",
        choice4: "Mercury",
        answer: "Mercury",
    },
    {
        question: "jcWhich planet has the most visible rings?",
        choice1: "Saturn",
        choice2: "sun",
        choice3: "earth",
        choice4: "mercury",
        answer: "Saturn",
    },
    {
        question: " What is the name of our galaxy?",
        choice1: "satrun",
        choice2: "sun",
        choice3: "earth",
        choice4: "Milky Way",
        answer: "Milky Way",
    },
    {
        question: "What planet is known as the red planet?",
        choice1: "sun",
        choice2: "mars",
        choice3: "earth",
        choice4: "juptier",
        answer: "mars",
    },
    {
        question: "Which planet is named after the Roman goddess of beauty?",
        choice1: "Venus",
        choice2: "mars",
        choice3: "sun",
        choice4: "earth",
        answer: "Venus",
    },
    {
        question: "Which is the second biggest planet in the solar system?",
        choice1: "sun",
        choice2: "earth",
        choice3: "Saturn",
        choice4: "mars",
        answer: "Saturn",
    },

]